### PR TITLE
Fix analytics point requests

### LINKED ISSUE #122: Send point data in time series request

### PR DESCRIPTION
**Pull request by Zodiase**
Due to backend not supporting reading query parameters from the url when dealing with `POST` requests, I had to use the `GET` method and put lat. and long. values in the url.

Ugly fix, should revert changes in `dataset.analytics.js`.

This resolves #122.

### CODE REVIEW

**Comment by tmcphillips** [comment]
I don't understand this.  Do POST requests not work for you? Why can't the lat and long go in the body of the POST request?  See the [timeseries.post.tests.js](https://github.com/openskope/timeseries-service/blob/master/src/__tests__/timeseries.post.tests.js) for examples of what works.

**Comment by Zodiase** [comment]
@tmcphillips The major reason is the client side doesn't have the dataset ID and the variable name used by the time series. E.g. I have dataset ID `nLpgKGIBGqV3oPMyBZbv` and variable name `Annual Precipitation`, would the backend be able to get the data from these info?

The second major reason is, in an effort to reduce coupling between client side and any backend service, I'm using a "server you tell me what I can offer you, I then give everything I could find" strategy. In Overlays Tab, for example, an overlay item has a url property that looks like this: `http://some.domain.com/some/path?some={foo}&query={bar}&varname=paleoCAR_{YYYY}`. It could also looks like this (even though it's not exactly the case of the overlays): `http://some.domain.com/dataset/{datasetId}/{YYYY}/{MM}-{DD}/some.file`. To generally support these potential urls while knowing as little about the urls as possible, I can't really try to parse the url into segments or query arguments. Instead I'm treating it as a normal string and only fill in the placeholders when available. As a result, everything is setup around the `fillTemplateString` function, as you may find in the list of changes. The idea is, if the `url template` has any placeholders I can fill, I try to fill it. This eliminates the requirement for the client side to know what is expected by the backend as much as possible.

As I'm trying to expand this algorithm to support request bodies, I realized that I can't really use it for a couple of reasons:

1. The dataset manifest has to include an additional field to store the request body template.
2. If I treat the entire body content as a string and proceed to do the placeholder replacement, it's possible for the output to be an invalid JSON string.
3. If I treat the entire body as an object and scan through its properties and do placeholder replacements along the way, that effectively enforces all values in the object to be strings. I think it's too much of a compromise.

So I ended up with a slightly altered algorithm that avoids these issues as much as possible:

1. Start from finding placeholders in the `url template`,
2. If the value of the placeholder is a string, it can go straight into the url without losing its type info. (I have forgotten to escape the values when doing replacements, need to fix that).
3. Otherwise, storing the value in the url in a string form may lose info or distort info (e.g. converting `null` to `"null"`). So store the value as is in the body object, while replacing the placeholder with an empty string.

Here's an example with this algorithm:

Input:
`"http://time-series.openskope.org/?dataset=foo&variable=bar&boundaryGeometry={boundaryGeometry}&start=0&end=1999"`

Output:
```
POST

"http://time-series.openskope.org/?dataset=foo&variable=bar&boundaryGeometry=&start=0&end=1999"

{
    "boundaryGeometry": {
        "type": "Point",
        "coordinates": [0, 0],
    }
}
```

In this example, the url template includes the dataset ID and the variable name since the client side doesn't know these. If the backend is checking both the url and body for the parameter it's looking for, them it should find `dataset`, `variable`, `start` and `end` in the url and `boundaryGeometry` in the body. But from my testing it looks like when the request method is `POST`, the backend is only looking at the body. I know this is what we agreed on but unfortunately I can't really follow it through as the dataset ID and variable name the backend is using don't align with the info the client side gets from the dataset manifest.

**Comment by tmcphillips** [comment]
I don't understand everything you're saying here, but I can offer a few options that might help.

First, we can have the timeseries-service use any names that  you like for the datasets and variables, and I can document what the filenames for the geotiffs need to be based on those names.  Let me know what the names you want to send for the dataset and four variables we have now and I'll make that work.

Second, we can support POST requests with some parameters coming from the query line and others from the body (or even from both, but we'll need to agree which takes priority).  Just let me know what you want.  More valid combinations means writing that many more tests, but that's not really a big deal.  To me, working tests are the things that are real and even close to being permanent.  Everything else is incidental and temporary.

Overall, I'm wondering if the design on the client side needs to be as general as you are making it?  Isn't expanding variables while defining a new Javascript object (e.g. for the POST body) really easy?

**Comment by abrin** [comment]
Why not just POST payload.boundaryGeometry? I don’t want to make work for Tim, but this should be trivial to handle on the server side.

**Comment by Zodiase** [comment]
@abrin Yes eventually I hope the server side should be taking parameters from both url and the body so simply `post`ing the geometry should work (as shown in the example in my previous comment). I wasn't sure there'd be enough time to get it done and deployed by tomorrow's meeting so had to go with the current approach. It's no big deal.

**Pull request merged**
